# Generated by Django 2.2 on 2019-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20190425_0421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
