# Generated by Django 2.2 on 2019-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20190428_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='length',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='hall',
            name='width',
            field=models.IntegerField(default=5),
        ),
    ]
