# Generated by Django 2.2 on 2019-04-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190426_1751'),
        ('movie', '0002_auto_20190426_2212'),
    ]

    operations = [
    ]
