# Generated by Django 2.2 on 2019-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_merge_20190427_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=999),
        ),
    ]
