# Generated by Django 2.2 on 2019-04-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0003_delete_session'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('price_student', models.IntegerField(null=True)),
                ('price_child', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('P', 'PAST'), ('C', 'CURRENT'), ('F', 'FUTURE'), ('C', 'CANCEL')], default='FUTURE', max_length=7)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
