# Generated by Django 2.2 on 2019-04-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20190427_1147'),
        ('session', '0005_auto_20190427_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='cinema',
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.Hall'),
        ),
    ]
