# Generated by Django 2.2 on 2019-04-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20190427_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatreserve',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to=settings.AUTH_USER_MODEL),
        ),
    ]
